# Generated by Django 2.1.2 on 2018-11-06 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TODOList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='what',
            name='title',
            field=models.CharField(default='untitled', max_length=20),
        ),
        migrations.AddField(
            model_name='what',
            name='what',
            field=models.CharField(default='anything-random', max_length=120),
        ),
        migrations.AddField(
            model_name='what',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
