# Generated by Django 2.1.2 on 2018-11-06 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TODOList', '0003_auto_20181106_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='AUTHOR',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
