# Generated by Django 2.1.2 on 2018-11-06 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODOList', '0004_list_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='AUTHOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
