# Generated by Django 2.1.2 on 2018-11-08 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODOList', '0006_auto_20181107_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='AUTHOR',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
