# Generated by Django 2.1.2 on 2018-11-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOList', '0007_auto_20181108_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='NUMBER',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1, max_length=1),
        ),
    ]
