# Generated by Django 2.1.2 on 2018-11-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOList', '0008_list_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='NUMBER',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1),
        ),
    ]
